### ISSUE TITLE
ES2015 minification: Incorrect operator precendence between (=>) and (,)

### ISSUE THREAD

**Issue by chbrenon** [xoofx/NUglify#12]
This issue was carried over from AjaxMin (and a bug report was filed, but it doesn't seem to be actively maintained).
When trying to minify JavaScript using arrow function syntax, the output of the code

``` javascript
(eve) => {
    delete eve.x;
    return eve;
}
```

gets minified to

``` javascript
n=>delete n.x,n
```

However, due to the precedence of these operators, running `n({x:1, y:2})` returns `true`, not `{y:2}`, as in the original function.

I apologize if this project is not meant to support ES2015/harmony JavaScript.

**Comment by samjudson** [comment]
Is this related to the issue I am seeing here:

https://github.com/madskristensen/BundlerMinifier/issues/301

Sam

**Comment by Almeonamy** [comment]
Can this issue be closed?
