### ISSUE TITLE
HTML minification behavior differs between 1.5.1 and 1.5.3 releases

### ISSUE THREAD

**Issue by scottaddie** [xoofx/NUglify#16]
Consider the following input HTML:

```html
<span tabindex="2">
    <i>
        hat
    </i>
</span>
```

Using the v1.5.1 NuGet package, the following output is produced:
```html
<span tabindex=2><i>hat</i></span>
```

Using the v1.5.3 NuGet package, the following output is produced:
```html
<span tabindex=2><i>hat </i></span>
```

Why is there a single space after "hat"?

**Comment by xoofx** [comment]
Most likely a regression introduced in the meantime...

**Comment by scottaddie** [comment]
Thank you for the quick response. It's also worth noting that the v1.5.2 NuGet package works the same as v1.5.1. Without digging into it, I'd guess that commit https://github.com/xoofx/NUglify/commit/df0fca6d76eb9fc1d68896d34d75cbe299a7d1a6 introduced the problem.

**Comment by xoofx** [comment]
I should be able to provide a fix later tonight...

**Comment by scottaddie** [comment]
Sounds great! Once a new NuGet package is made available, I will fix and close the issue in the BundlerMinifier repo.

**Comment by xoofx** [comment]
Package 1.5.4 is already available 😉
