### ISSUE TITLE
Nuglify.csproj doesn't include all files

### ISSUE THREAD

**Issue by MarioZG** [xoofx/NUglify#18]
Just did get clean clone, tried to build and it failed. It  turns out that Nuglify.csproj do not have many files included (Html subfolder has only one file added, there is much more on disk)

Also solution and project reference some non-exiting files (i.e.: global.json)

**Comment by xoofx** [comment]
The solution `NUglify.xplat.sln` should work assuming that you have installed dotnet core SDK.

**Comment by MarioZG** [comment]
I'm missing dotnet core SDK. At the end, I made it build. I just wanted to let you know about this issue.  If you are aware of this, I'm happy if you close this one.

**Comment by xoofx** [comment]
Just to be sure, which sln did you open in the first place?

**Comment by MarioZG** [comment]
NUglify.net40.sln

**Comment by xoofx** [comment]
Thanks, the sln is removed on latest master with commit  	8c7379f
