### ISSUE TITLE
Should not carry the Uglify name unless it's an actual port of UglifyJS

### ISSUE THREAD

**Issue by rjgotten** [xoofx/NUglify#2]
If you're going to name this NUglify, it should be a feature-compatible .NET port of the UglifyJS minifier. Otherwise, you're just going to end up confusing people.

**Comment by xoofx** [comment]
The first thing you can read in the readme is stating that: This repository is a fork of the Microsoft Ajax Minifier. So I assume that it should be pretty clear and obvious that it is not a port of the Uglify js library.
Just to understand, you are a .NET developer looking for a port of Uglify.js and you have been confused?

**Comment by rjgotten** [comment]
I wasn't actively looking for a port of UglifyJS, but I ran across this as the 'package of the week' on the .NET blog and it picqued my interests.

Also; readme files don't say a whole lot to people scanning through the Nuget gallery, where the package is simply labeled as "NUglify is a JavaScript and CSS minification Library for .NET"

**Comment by xoofx** [comment]
I have updated the description about the fork from AjaxMin on both github and NuGet.
