### ISSUE TITLE
Empty String

### ISSUE THREAD

**Issue by Ahsan543** [xoofx/NUglify#22]
var dummy = "RED! Take the RED Pill!";
   var res = Uglify.HtmlToText(dummy).ToString();
working fine on all scenarios but if put above dummy string it shows empty string 
i dont understand why

**Comment by xoofx** [comment]
I don't remember exactly the behavior of this with such a text, but I believe that it expects an HTML document, and as it is not, it strips everything that is not part of a valid HTML tag. If your text is a HTML fragment, you have to pass an `HtmlSettings` with `IsFragmentOnly` set to `true`
