### ISSUE TITLE
sources attribute of V3SourceMap is incorrect  

### ISSUE THREAD

**Issue by asprna** [xoofx/NUglify#25]
I'm currently using v1.5.5 to generate source map. 

```
var filePath = @"<SOMEPATH>\Website\Assets\scripts.js";
var fileContent = "<SOME JAVASCRIPT CONTENT>"
using (TextWriter mapWriter = System.IO.File.CreateText(javascript.Replace(filePath, ".js.map"))) {
         using (var sourceMap = new V3SourceMap(mapWriter)) {
                    var settings = new CodeSettings();
		    settings.SymbolsMap = sourceMap;
		    sourceMap.StartPackage(filePath, filePath.Replace(".js", ".js.map"));

		   fileContent = Uglify.Js(fileContent, settings).Code;
	}
}
```
This produces a map file with below format

{
"version":3,
"file":"scripts.js",
"lineCount":17,
"mappings":";;;;;;;;;AA0PAA,SAASA,SAAS,CAACC,CAAE,CAAEC,CAAL,CAAc,CAC/B,IAMI...",
**_"sources":["../../../../../../../../../windows/system32/inetsrv/input"]_**,
"names":["makePopup","id","settings","opts","modal_popup","p_modal","s","hol"]
}

Here, sources attribute is wrong hence source map is not working in the browser. If I update that to scripts.js, then it will solve the issue.

Could you please confirm if this is an bug in this build or I'm doing something wrong here?

Thanks in advance.

**Comment by xoofx** [comment]
You should not use a full filepath but only a filename (e.g `scripts.js`) for the `sourceMap.StartPackage` parameters

**Comment by asprna** [comment]
Thanks for the quick response, I tried it with just a file name, but still sources attribute is wrong. 

e.g
var sourcePath = @"someSource.js";
var mapPath = @"someSource.map.js";

// just some random source
var sourceCode = "var foo = 42;function globalFunc(text){ alert(text); }";

string minifiedCode = null;

var mapBuilder = new StringBuilder();
using (var mapWriter = new StringWriter(mapBuilder)) {
	using (var sourceMap = new V3SourceMap(mapWriter)) {
		var settings = new CodeSettings();
		settings.SymbolsMap = sourceMap;
		sourceMap.StartPackage(sourcePath, mapPath);

		minifiedCode = Uglify.Js(sourceCode, settings).Code;
	}
}

Console.WriteLine(mapBuilder.ToString());

Below is the result, where  sources should be "sources":["someSource.js"]
{"version":3,
"file":"someSource.js",
"lineCount":1,
"mappings":"AAAaA,SAASA,UAAU,CAACC,CAAD,CAAM,CAAEC,KAAK,CAACD,CAAD,CAAP,CAAtC,IAAIE,IAAM",
"sources":["input"],
"names":["globalFunc","text","alert","foo"]
}

**Comment by asprna** [comment]
I just realised there is another constructor to pass the file name for the sources attribute.

minifiedCode = Uglify.Js(sourceCode, "someSource.js", settings).Code;

Thanks for your help and time
