### ISSUE TITLE
HTML HEAD and BODY tags gets removed

### ISSUE THREAD

**Issue by bloudraak** [xoofx/NUglify#27]
Consider the following code:

```
var source = File.ReadAllText("index.html");
var r = NUglify.Uglify.Html(template.Source, null);
var s = r.Code ?? source;
```

The file `index.html` looks as follows:
```
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Werner Strydom</title>
</head>
<body>
    <header>
        <h1>Werner Strydom</h1>
    </header>
    <main>
        <h1>Home Page</h1>
<p>Werner Strydom is a software engineer at Change Healthcare with an interest</p>
<ul>
<li>identity management</li>
<li>operational and cloud security</li>
<li>release engineering</li>
<li>site reliability engineering</li>
</ul>

    </main>
    <footer>
        <p>Copyright 2017 Werner Strydom</p>
    </footer>
</body>
</html>
```
The output looks as follows:
```
<!DOCTYPE html><html lang=en-us><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1.0"><title>Werner Strydom</title><header><h1>Werner Strydom</h1></header><main><p>Hello World</main><footer><p>Copyright 2017 Werner Strydom</footer>
```
Notice that the HEAD and BODY tags as well as the closing HTML tag were removed. 

NUglify 1.5.5

**Comment by xoofx** [comment]
It should be the correct behavior, as HEAD, BODY start/end tags are optional as per the specs (as well as HTML if there are no attributes).

**Comment by bloudraak** [comment]
The specs do say that, but the resulting document has its issues with IE that could care less about the specs. 

Is there a quirks or compatibility mode where I can state that some elements should be preserved in order to ensure maximum compatibility?

**Comment by xoofx** [comment]
You can use `HtmlSettings.RemoveOptionalTags = false` but this will apply to all tags.

I have also pushed a new version with the `HtmlSettings.KeepTags` property, so you can keep optional tags:

```c#
settings.KeepTags.Add("html");
settings.KeepTags.Add("head");
settings.KeepTags.Add("body");
```
