### ISSUE TITLE
Issue Minifying css including Glyphicons content

### ISSUE THREAD

**Issue by mbp** [xoofx/NUglify#28]
This is basically re-opening a previous issue #14 which I don't know why was closed.

The origin of the bug comes from https://github.com/madskristensen/BundlerMinifier/issues/270

# Description
Incorrect value for glyphicon content after minification

# Steps to recreate

    static void Main(string[] args)
    {
        var content = ".glyphicon-search:before { content: \"\\e003\"; }";

        var result = Uglify.Css(content);

        Console.WriteLine(content);
        Console.WriteLine(result.Code);

        Console.Read();
    }

Actual output

    .glyphicon-search:before { content: "\e003"; }
    .glyphicon-search:before{content:""}

# Expected Behaviour

Gyphicon content should still be the same as it was before minification

**Comment by xoofx** [comment]
afaik, it is the same, just that it is a plain UTF8 characters after the transform and it should load correctly assuming charset is correctly setup, no?

**Comment by mbp** [comment]
Yes I would also assume that, but apparently not (see the BundlerMinifier bug report).
I experienced exactly the same - couldn't make it work. Only when the `content` field was a string literal, it worked in all browsers.

I see some related discussion here, but I have not used more time to understand the underlying issue: https://github.com/twbs/bootstrap/issues/10106#issuecomment-33576265

**Comment by xoofx** [comment]
Note for fix, check whether adding `@charset "UTF-8";`  ([charset](https://developer.mozilla.org/en-US/docs/Web/CSS/%40charset)) is fixing this. Change minifier to take into account the cost of adding the charset

**Comment by mojtabakaviani** [comment]
``@charset "UTF-8";`` not solved this problem!
