### ISSUE TITLE
1.5.5 -> 1.5.6 included breaking change, violates SEMVER

### ISSUE THREAD

**Issue by wldkrd1** [xoofx/NUglify#29]
From SemVer.org:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
>     MAJOR version when you make incompatible API changes,
>     MINOR version when you add functionality in a backwards-compatible manner, and
>     PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the > MAJOR.MINOR.PATCH format.

The rename from UgliflyResult() to UglifyResult() is an incompatible API

**Comment by wldkrd1** [comment]
Recommend turning this into a MINOR increment by reinstating the UgliflyResult() method, marking it as deprecated, and having it merely call the renamed version

**Comment by trullock** [comment]
This has happened, not much I can do now.

Closing
