### ISSUE TITLE
HtmlToText

### ISSUE THREAD

**Issue by ThiloL** [xoofx/NUglify#38]
How to make HtmlToText work with invalid (non standard) HTML code?

**Comment by xoofx** [comment]
In which case it doesn't work for you?

**Comment by ThiloL** [comment]
I have HTML code like "...<span><div>text</div>.....</span>". HtmlToText reports the error "(10,1): warning: The tag <div> is not a valid tag within...."

**Comment by xoofx** [comment]
But this prints a warning so it should still be able to run, that's not a hard error right? What is the generated actual output?

**Comment by ThiloL** [comment]
Yes. HasErrors is false. Errors has content. But Code is a empty string.

**Comment by xoofx** [comment]
Could you post a simple reproducible test with `Uglify.HtmlToText`. Trying from the snippet above and the text is extracted correctly, so the problem is somewhere else...

**Comment by ThiloL** [comment]
`using System;
using NUglify;

namespace UgilfyTest
{
    class Program
    {
        static void Main(string[] args)
        {

            string Input = @"<style>\r\n\r\n</style>\r\n<div><font size=\""2\""><span style=\""font-size:10pt\"">\r\n
<div class=\""x_PlainText\"">Liebe Kunden und Kollegen,\r\n in München. Danke für Ihr Verständnis.<br>\r\n<br>\r\nViele Grüße, Astrind Testfrau</div>\r\n</span></font></div>";

            var Result = Uglify.HtmlToText(Input, NUglify.Html.HtmlToTextOptions.KeepStructure);

            // Result.Code is emty
            Console.WriteLine(Result.Code);

        }
    }
}
`

**Comment by xoofx** [comment]
Ok, so there is currently a limitation in the code that requires at least a global enclosing element `<body>` (so that it doesn't try to output the head for example, but only the body), so if you wrap your HTML fragment with `<body>....</body>` you should have the text correctly extracted.

**Comment by ThiloL** [comment]
OK. Thanks!
