### ISSUE TITLE
can not bundle javascript async await

### ISSUE THREAD

**Issue by bastienJS** [xoofx/NUglify#39]
Installed product versions
Visual Studio: 2017 Comunity Edition (15.4.4)
This extension: Bundler & Minifier 2.5.359 (Latest version of Extension available in VS Marketplace)
Description
Error:

(Bundler & Minifier) Expected ';'

When minifing a java script file with async and await keywords, finds error.

original unminified file works as expected in web browsers.

Steps to recreate
Create new js file
write any function with async await
example:

async function someName() {
    const response = await fetch('../some/URL');
    return await  response.json();
}
Current behavior
Error appears and wont minify

Expected behavior
Should minify

**Comment by iliDaedalus** [comment]
2years later... and I wonder if there are any news regarding this issue?

**Comment by nul** [comment]
This actually works correctly with the latest version.
