### ISSUE TITLE
ECMAScript 6 Support for computed names in object property definitions.

### ISSUE THREAD

**Issue by daniel-tikhonov** [xoofx/NUglify#42]
Support for computed names in object property definitions.
Source:
`let obj = {
    foo: "bar",
    [ "baz" + quux() ]: 42
}`
Dest:
`let obj={foo:"bar"}["baz"+quux()];42`

**Comment by xoofx** [comment]
There are several known issues around support for ES6. If you want this to be fixed, please consider contributing via a PR as I don't have time/interest to provide fixes on these issues.
For more details, see the [CONTRIBUTING](https://github.com/xoofx/NUglify/blob/master/CONTRIBUTING.md) notice.

**Comment by samjudson** [comment]
This issue should be resolved now.

**Comment by rockstardev** [comment]
OK @samjudson - thanks for all your hard work... let me know when you are done with changes and I'll also publish new version of BundlerMinifier.

**Comment by samjudson** [comment]
Thanks @rockstardev . There are number of ES2015+ES2017 issues outstanding, see #52 . Could take a while to get through all of them so feel free to make releases of the bundler in the meantime.
