### ISSUE TITLE
ES6 arrow functions

### ISSUE THREAD

**Issue by daniel-tikhonov** [xoofx/NUglify#43]
Source: `logs.map(l => {return {a: l.name, b: l.id}})`
Minified: `logs.map(l => {a: l.name, b: l.id})`

**Comment by xoofx** [comment]
There are several known issues around support for ES6. If you want this to be fixed, please consider contributing via a PR as I don't have time/interest to provide fixes on these issues.
For more details, see the [CONTRIBUTING](https://github.com/xoofx/NUglify/blob/master/CONTRIBUTING.md) notice.

**Comment by rockstardev** [comment]
@daniel-tikhonov would you be willing the help solve this issue by sending Pull Requests? I could code some parts definitely, but would appreciate at least some help both with coding and testing.

**Comment by trullock** [comment]
Shall we try and fix this? There's probably enough people suffering with it. I'm happy to have a go if someone points me in the right direction in the codebase, @xoofx any hints on where to start?
