### ISSUE TITLE
Ability to Ignore non-HTML tags in HtmlToText()

### ISSUE THREAD

**Issue by shoaibshakeel381** [xoofx/NUglify#44]
Sometimes our html might contain text which is enclosed in angle brackets. E.g.

> "Brother Mo, could it be that you are cultivating with the &lt;Basics of Cultivation&gt;?” From his posture, Ji Guang could guess that Mo Wuji was a practitioner of the &lt;Basics of Cultivation&gt;.

When we try to get text from this HTML using ``Uglify.HtmlToText(content);`` It would completely remove text which is inside angle brackets. Resulting in:

> “Brother Mo, could it be that you are cultivating with the ?” From his posture, Ji Guang could guess that Mo Wuji was a practitioner of the .

Is there a way to handle this?

**Comment by trullock** [comment]
Yes, use &lt; and &gt; for valid HTML input in the first place.
This isn't a bug
