### ISSUE TITLE
Async/Await operations break minification

### ISSUE THREAD

**Issue by spanishprisoner** [xoofx/NUglify#55]
async/await keywords in js files break minification. There is a pull request for that already:
https://github.com/xoofx/NUglify/pull/53
waiting for nearly a month now. Any issues with it, or what's the problem?

**Comment by brightertools** [comment]
Is there any ETA on a fix for this?

**Comment by spanishprisoner** [comment]
Haven't used this is quite a while but the pr in question has been merged so closing the issue.
