### ISSUE TITLE
Minifiying css with @supports and :not selector removes important whitespace

### ISSUE THREAD

**Issue by lajjne** [xoofx/NUglify#56]
Minifying the following css with `OutputMode.SingleLine` removes important whitespace just before **body** .

```
@supports (position: sticky) {
  html:not(.windows) body { 
    top: 9rem;  
  }
}
```

result: 
```
@supports(position:sticky){html:not(.windows)body{top:9rem;}}
```

expected: 
```
@supports(position:sticky){html:not(.windows) body{top:9rem;}}
```

**Comment by trullock** [comment]
it actually outputs

`@supports (position:sticky){html:not(.windows) body{top:9rem}}`

Which is valid css.

Admittedly the space between `supports` and `(` could go, but that's not the issue.

Closing this as already fixed, pushed a test which [fails to] repro this.

Reopen if this is still an issue
