### ISSUE TITLE
for(let x of y.prop) being incorrectly replaced with for(let t of t.prop)

### ISSUE THREAD

**Issue by rexxmagnus** [xoofx/NUglify#6]
This bug came about via the Visual Studio Bundler and Minifier extension, but is apparently a bug in this library:

**Description:**

Variables in for (x of y.property) loop are being replaced with for(let t of t.prop) and causing problems when t gets overwritten.
Steps to recreate

Minify the following snippet:

```
function successCallback(response) {
   if (response.data) {
      for (let thing of response.data) {
         if (!someArray.find(function (item) { return item.prop == thing.prop; })) {
            someArray.push(thing);
         }
      }
   }
}
```

**Current behavior**

Minifies to:
`function successCallback(n){if(n.data)for(let n of n.data)someArray.find(function(t){return t.prop==n.prop})||someArray.push(n)}`

let n of n.data is incorrect. The "let n" should be replaced by another letter, as n effectively overwrites the variable being referred to by "response" in the original code, breaking the reference.

If the for loop contains a direct reference to response.data (as opposed to the reference inside the anonymous inner function) the code gets minified correctly.

**Expected behavior**

Adding in references to the looped objects (console.logged) gives correct output:

```
function successCallback(response) {
   if (response.data) {
      for (let thing of response.data) {
         console.log(thing);
         console.log(response.data);
         if (!someArray.find(function (item) { return item.prop == thing.prop; })) {
            someArray.push(thing);
         }
      }
   }
}
```

`function successCallback(n){if(n.data)for(let t of n.data)console.log(t),console.log(n.data),someArray.find(function(n){return n.prop==t.prop})||someArray.push(t)}`

**Comment by xoofx** [comment]
Not sure to understand why this is incorrect? the `response.data` in the for loop is evaluated _just once_ when entering the loop and then the variable `thing` is filled with the iteration on this returned value.

If you type `var x = { prop: [1,2,3] }; for(var x in x.prop) { console.log(x); }` in the console of a browser, it will print the correct values.

**Comment by rexxmagnus** [comment]
The minified code is reusing the same variable name as the variable whose properties/items are being iterated through. Part of the problem with using var is that the variable is hoisted to the function level, and not kept within the for loop. If the variable gets hoisted, the replacement variable label overwrites the response variable, so references outside the loop no longer work correctly.
I had to use let inside the for loop to prevent hoisting, but without a reference inside the loop it doesn't minify correctly.

**Comment by xoofx** [comment]
Yes, but again, the response variable is not read after `response.data` is read (the loop is using it only just once at loop init) so there should not have any problem. The sample above with x is working fine, as long as x is not accessed after (same as your sample)

**Comment by rexxmagnus** [comment]
I'll have to test it again with an expanded section of code because it did cause issues for me with the variable being overwritten. I just reduced this segment to an isolated case to demonstrate it.

**Comment by rexxmagnus** [comment]
Sorry, I need to reopen this ... I've just run into the issue with a very minimal example:

```
function go(scope) {
    for (let n of scope.a) {
        console.log(n);
    }
}

go({ a: [1, 2, 3] })
```
Output should be 1, 2, 3 on separate lines.

Minifies to:
`function go(n){for(let n of n.a)console.log(n)}go({a:[1,2,3]});`

Try this in a browser's console (does it in firefox and chrome) - it returns n is undefined, most likely because of the attempted variable hiding by the use of reference n.

**Comment by rexxmagnus** [comment]
I've just had a look at the source code (struggling to get my head around exactly how it works) but I *think* the problem with this may be in Javascript/Visitors/AnalyzeNodeVisitors.cs CombineExpressions method.

There is a line: var previousVar = node[ndx - 1] as VarDeclaration;
This will return null if the variable is a LexicalDeclaration, which is what "let" falls into, and therefore doesn't get handled like a var when its in the context of a for loop. I suspect it needs to be handled in the same fashion to prevent variable name reuse.

**Comment by JimAnkrom** [comment]
I've just filed similar here with BundlerMinifier, which uses NUglify - https://github.com/madskristensen/BundlerMinifier/issues/389

It's clear to me there's something very wrong indeed with scope and this minifier, it's reusing variable names from parent scopes in lexical declarations. 

This is a showstopper for me, I need to find a new minifier over this.

**Comment by robinwilson16** [comment]
I have just run into this same issue as well with the Bundler and Minifier where incorrect syntax is being generated but have found a workaround.

It appears the bug is triggered with ```for (let x of y)``` which is minified to ```for (let x of x)``` but if you replace ```let``` with ```var``` (```for (var x of y)```) then it minifies as expected with valid syntax.

I logged my issue here:
[BundlerMinifier/issues/395](https://github.com/madskristensen/BundlerMinifier/issues/395)

With the original bug over 2 and a half years old is a fix likely? I took quite  lot of time troubleshooting my code until I realised it was a bug in the library. Otherwise the minifier is really useful.

**Comment by xoofx** [comment]
> Is no-one maintaining this package?

Yes, no one is maintaining it. It happened that I just saved the previous AjaxMin project from codeplex death, I had a usage of this library a few years ago, but I don't have anymore. So that's why, it's really up to you folks relying on it... or for you to find an alternative.

**Comment by robinwilson16** [comment]
Ok thanks for the reply. To meet the deadline I have just gone with unminified code for now. It looks like there is a more recent addon for VS Code but can't find much for VS.
Not sure if I would be able to fix although with libman being recommended for bundling maybe only the minification is needed now. 
I suppose I could copy and paste into a minifier on the web but then I would need to remember to always do that.
Maybe VS 2019 will offer an alternative.

**Comment by CRACKISH** [comment]
I have some bug too ((

Original code

`
getDistinctHyperlinks: function(allLinks) {
	const result = [];
	const map = new Map();
	for (const item of allLinks) {
		if (!map.has(item.Url)) {
			map.set(item.Url, true);
			result.push({
				Url: item.Url,
				Caption: item.Caption
			});
		}
	}
	return result;
}
`

minified code

`
getDistinctHyperlinks: function(n) {
	const t = [],
		i = new Map;
	for (const n of n) i.has(n.Url) || (i.set(n.Url, !0), t.push({
		Url: n.Url,
		Caption: n.Caption
	}));
	return t
}
`

error in **for (const n of n)**
