### ISSUE TITLE
Incorrect translation of unicode constants

### ISSUE THREAD

**Issue by kendallb** [xoofx/NUglify#62]
This issue has been present in AjaxMin since we have used it, and I ran across this project which is a fork of the code so hoped that perhaps it has been resolved. However it looks like it has not, so I thought I would report this issue in case anyone else has ran across it and knows how to solve it? If not, it would be good to take a look at fixing it in this improved code base.

Anyway, we have .less file content that looks like this:

            &:after {
                content: "\25BC";
            }

when this is put through the minifier, it ends up replacing "\25BC" with "?", as it fails to translate the Unicode string constant correctly. We are currently using the Yui minifier which works around this issue, but it would be good to get this fixed in this library also.

**Comment by xoofx** [comment]
> but it would be good to get this fixed in this library also.

As explained in the readme, this issue will likely be fixed only if you are willing to take the time to fix it. Otherwise, as there are no real maintainers of this project, this will never get fixed.

**Comment by kendallb** [comment]
Fair enough. I will have to see if I can find the time to dig into this myself, but so far the Yui compressor resolved the issue. I do have some other JS minification stuff that caused issues in the past with AjaxMin, so if I can find those files and replicate those issues again I will take a look at both at the same time.

Thanks for resurrecting this project though!

**Comment by trullock** [comment]
Was this issue fixed in March ^? Can we close this?

**Comment by kendallb** [comment]
Go ahead and close it. We are moving to webpack soon and I assume the patches fixed it.
