### ISSUE TITLE
Minifier turns (0, eval) into eval

### ISSUE THREAD

**Issue by BorisMoore** [xoofx/NUglify#7]
See corresponding issue on AjaxMin: https://ajaxmin.codeplex.com/workitem/22084

See also https://github.com/madskristensen/BundlerMinifier/issues/63#issuecomment-226567914 and https://github.com/BorisMoore/jsviews/issues/323

**Comment by xoofx** [comment]
This should be fixed by commit cc74cf1

**Comment by BorisMoore** [comment]
Great, thanks. I have changed JsRender so it no longer depends on this, but other users would potentially have been hit by the same problem - so good to know it is fixed...
