### ISSUE TITLE
Async identifier is removed in some cases

### ISSUE THREAD

**Issue by GilianJuice** [xoofx/NUglify#77]
That problem has been said to be fixed in https://github.com/xoofx/NUglify/pull/65, but it's not fully fixed;  If you create a class with an async function inside, it will remove the "async" keyword from the javascript, which causes errors if you try to use await in that same function.

I have created a class to test this (and some other ES6 things). The init function is async, but that will break. Inside the init function I create a local async function and that works fine.

`
class Test {
    constructor() {
        console.log("Constructor OK");
        this.init(123);
    }
    
    /** 
    * Test function
    * @param {any} Test 1.
    * @param {any} Test 2.
    */
    async init(test1, test2 = 1337) {
        // This is a test comment./
        const tempAr = ["this", "is", "an", "array", test1, test2];

        console.log(tempAr.filter(e => e === "an"));
        console.log(tempAr.map(e=> { return {"key": e }; }));
        
        for(let item of tempAr) {
            console.log(item);
        }
        
        const testFunction = async function() {
        	const result = await $.ajax({
                url: "https://google.com"
        	});
            
            console.log("ajax 2", result);
        };
        
        try {
        	const result = await $.ajax({
                url: "https://google.com"
        	});
            
            console.log("ajax 1", result);
            
            testFunction();
           	console.log("done");
        } catch (exception) {
            console.error("error", exception);
        }
    }
}

const test = new Test();
`

**Comment by davidfilkins** [comment]
@GilianJuice, did you ever come up with a work-around for this? I'm seeing the same issue.

**Comment by GilianJuice** [comment]
@davidfilkins No not really, I have looked for other minifiers, but they all have their own problems. NUglify is by far the best one that I've found. I was hoping this would get fixed soon, in the mean time i just disable the minifier for javascript files that use async/await.

**Comment by davidfilkins** [comment]
Works as advertised / like a charm. Thanks!

Cheers

**Comment by GilianJuice** [comment]
Thank you, I have just updated NUglify and it works perfectly!
