### ISSUE TITLE
for-let-in broken by rename when iterable is not property of another object

### ISSUE THREAD

**Issue by ChemicalRascal** [xoofx/NUglify#79]
Related to, but not strictly a duplicate of, #6 :

```
function go(scope) {
    for (let test in scope) {
        console.log(test);
    }
}
```

Minifies to `function go(n){for(let n in n)console.log(n)}go([1,2,3])` instead of the expected `function go(n){for(let t in n)console.log(t)}go([1,2,3])"`, and `let n in n` is, well, nonfunctional.

I've written a test and will take a stab at this over the weekend, just dropping this in now such that folks are made aware of the issue in the meantime.

**Comment by ChemicalRascal** [comment]
It _appears_ this stems from a slight error in the way ActivationObject.NameTable propagates through scopes. In that, at least in this minimal case, the crunched fields don't propagate down to the child scopes, thus the existing names (here `n`) doesn't get added to the avoid list.

It is, however, late Sunday. Probably won't get a PR together until next weekend.

**Comment by gulbanana** [comment]
thanks for finding this, i have the same issue and understanding the problem lets me use a workaround

**Comment by nelutzu91** [comment]
@ChemicalRascal, @gulbanana, I don't know if you managed to fix this issue, but as a workaround I found what copying the **scope** variable into another one, fixes the issue.
`function go(scope) {
    const inerrScope = scope;
    for (let test in scope) {
        console.log(test);
    }
}`

**Comment by ChemicalRascal** [comment]
@nelutzu91 -- Thanks for the workaround. I didn't actually manage to fix this in NUglify itself, unfortunately -- the naive fix (propagating the name table in certain cases that it wasn't being propagated) broke a _lot_ of test cases, and I couldn't wrap my head around the actual proper mechanics of everything otherwise. Sorry about that.

**Comment by trullock** [comment]
This is also a broken example:

```
function go(scope) {

    function fn (test) {
        console.log(test);
    }
    fn(scope);
}
```

this minifies to 

`function go(n){function t(n){console.log(n)}t(n)}`
