### ISSUE TITLE
Spread operator in objects is not working

### ISSUE THREAD

**Issue by Yaroshvitaliy** [xoofx/NUglify#84]
It seems spread operator in objects is not supported at all (but is working for arrays).
Consider the following C# code:
```
static void UglifyJs()
{
  var settings = new CodeSettings { ScriptVersion = ScriptVersion.EcmaScript6 };
  var res = Uglify.Js(JsCode, settings);
  Console.WriteLine(res.Code);
}

static string JsCode = @"

const obj1 = {
    prop0: 'val0',
    prop1: 'val1'
};
const obj2 = {
    ...obj1,
    prop2: 'val2'
};
";
```
result is the  following:

`const obj1={prop0:"val0",prop1:"val1"},obj2={};...obj1;prop2;"val2"`

As you can see, obj2 got empy.
Could you help with this issue?

**Comment by trullock** [comment]
Reported as fixed
