### ISSUE TITLE
Return support of .NET Standard 1.3

### ISSUE THREAD

**Issue by Taritsyn** [xoofx/NUglify#9]
In general, class libraries which target a lower [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) version, can be loaded by the largest number of existing platforms.

**Comment by xoofx** [comment]
Hm but it has never changed ([here](https://github.com/xoofx/NUglify/blob/f549ded01dcf63e218c3f7f05da6804d5381600b/src/NUglify/project.json#L73))

**Comment by Taritsyn** [comment]
It seems, that I was wrong. I was misled by the following text: “Add support to dotnet RTM, switch to netstandard1.6”.

**Comment by xoofx** [comment]
ah sorry indeed, the commit text was misleading!
