### ISSUE TITLE
Project has missing test files

### ISSUE THREAD

**Issue by trullock** [xoofx/NUglify#96]
All the files under `NUglify.Tests.TestData.HTML.tidy-html-5-tests` are missing, removing them from the proj to enable building leaves two broken tests

**Comment by xoofx** [comment]
Did you update your submodule correctly?

**Comment by xoofx** [comment]
Sure you can send a PR, but whenever you clone a repo, just always clone submodules. There is no reason to not clone them and most GUI IDE do that for you automatically.
